# Generated by Django 5.2.9 on 2025-12-02 14:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sensor Name')),
                ('resolution_type', models.CharField(default='resolution', max_length=30, verbose_name='Resolution Type')),
                ('resolution_value', models.FloatField(default=0, verbose_name='Resolution [m]')),
                ('swath', models.FloatField(default=0, verbose_name='Swath [km]')),
                ('positive_tilting', models.FloatField(default=0, verbose_name='Positive Tilting')),
                ('negative_tilting', models.FloatField(default=0, verbose_name='Negative Tilting')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('norad_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='NORAD ID')),
                ('name', models.CharField(max_length=20, verbose_name='Satellite Name')),
                ('satellite_type', models.CharField(default='-', max_length=30, verbose_name='Satellite type')),
                ('description', models.TextField(default='-', verbose_name='About Satellite')),
                ('tle_now', models.TextField(default='', editable=False, verbose_name='Satellite Tle')),
                ('launch_date', models.DateField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), verbose_name='Launch Date')),
                ('launch_site', models.CharField(default='not provided', max_length=50, verbose_name='Launch Site')),
                ('last_tle_update', models.DateField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), editable=False, verbose_name='Launch Date')),
                ('swath', models.FloatField(default=0, verbose_name='Swath [km]')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('not_tracked', 'NOT TRACKED')], default='IN ORBIT', max_length=20, verbose_name='Status')),
                ('orbit', models.CharField(default='-', max_length=20, verbose_name='Orbit Type')),
                ('orbital_period', models.FloatField(default=0, verbose_name='Orbital Period [m]')),
                ('orbit_revisit', models.IntegerField(default=0, verbose_name='Revisit Period [days]')),
                ('orbit_distance', models.FloatField(default=0, verbose_name='Successive orbits distance [km]')),
                ('orbits_per_day', models.IntegerField(default=0, verbose_name='Orbits per day')),
                ('inclination', models.FloatField(default=0, verbose_name='Inclination [°]')),
                ('perigee', models.FloatField(default=0, verbose_name='Perigee')),
                ('apogee', models.FloatField(default=0, verbose_name='Apogee')),
                ('sensors', models.ManyToManyField(to='satTrack.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tle', models.TextField(default='s', max_length=300, null=True, verbose_name='Satellite Tle')),
                ('epoch_date', models.DateTimeField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), verbose_name='Epoch Date')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satTrack.satellite')),
            ],
        ),
    ]
